version: "2"

formatters:
  enable:
    - goimports
    - gofumpt

linters:
  default: standard
  enable:
    - gosec
    - bodyclose
    - govet
    - staticcheck
    - errcheck
    - gocritic
    - gocyclo
    - err113
    - wrapcheck
    - modernize

  settings:
    gocyclo:
      min-complexity: 15

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters: [errcheck, gosec]
